#!/usr/bin/env bash
# Set permissions to -rwxr-x-wx
#!/bin/bash chmod 751 hello
#!/usr/bin/env bash
# Set permissions to -rwxr-x-wx
#!/bin/bash chmod 753 hello
#!/bin/bash chmod +x 9-John_Doe
#!/bin/bash ./9-John_Doe
